image: drone-sphinx

script:
  - make html
  - make latexpdf
  - echo "Done!"

deploy:
  bash:
    branch: master
    scripts:
        - "[ $DRONE_BRANCH == master ] && su sphinx -c /sphinx/sync_built_docs.sh"
        - "[ $DRONE_BRANCH == unify ] && su sphinx -c /sphinx/sync_unify_docs.sh"
