language: python

sudo: false

addons:
    apt:
        packages:
            - texlive
            - texlive-full
            - dvipng
            - graphviz
            - pandoc

env:
  matrix:
    - BUILD_CMD='html'
    - BUILD_CMD='latexpdf'
            
python:
    - 2.7

virtualenv:
     system_site_packages: false

install:
    - pip install -r requirements.txt

script:
    - wget http://math.sut.ac.th/lab/software/texlive/texmf-dist/tex/latex/caption/newfloat.sty
    - ls
    - mkdir -p _build/latex/
    - mv newfloat.sty ./_build/latex/
    - make $BUILD_CMD
