language: python

sudo: false

addons:
    apt:
        packages:
            - texlive-latex-extra
            - dvipng
python:
    - 2.7

virtualenv:
     system_site_packages: false

install:
    - pip install -r requirements.txt

script:
    - make html
    - make latexpdf
