language: python

sudo: false

addons:
    apt:
        packages:
            - texlive
            - texlive-full
            - dvipng
            - graphviz
            - pandoc

env:
  matrix:
    - BUILD_CMD='html'
    - BUILD_CMD='latexpdf'
            
python:
    - 2.7

virtualenv:
     system_site_packages: false

install:
    - pip install -r requirements.txt

script:
    - make $BUILD_CMD
